sudo: required
language: go

go:
 - 1.11.x

env:
  - GO111MODULE=on

install: true

services:
 - docker

script:
 - make
 - make test

notifications:
  email:
    on_success: change
    on_failure: always
